[package]
name = "colorlight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rawsock = "0.3.0"
rayon = "1.8.0"
v4l = "0.14.0"
